# Github action to build github activity
#

name: github activity

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout source
      uses: actions/checkout@v2
   
    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install github-activity
      run: pip3 install --user -r requirements.txt
      
    - name: graph 
      run: mkdir source && cd source && mkdir charts 
      
    - name: graph 
      run: python monthly.py
      
    - name: fortran 
      run: python fortran_package.py
    
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "henilp105" 
        git add fortran-lang.org.json
        git add fpm.json
        git add source
        git add stdlib.json
        git add fortran.json
        git commit -m "graphs and fortran"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.METRICS_TOKEN }}
        force: true
